/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "0caef298c2ff935b622673e09cd542151dc2ecc0-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
