/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "6a122884e44b7592dcad6c6ffe3fc80fba7b2b2f"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
